"""
Helper script to create .env file with required configuration.
Run this to set up environment variables.
"""

import os

def create_env_file():
    """Create .env file with default configuration."""
    env_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), ".env")
    
    if os.path.exists(env_path):
        print(f"⚠️  .env file already exists at {env_path}")
        response = input("Do you want to overwrite it? (yes/no): ")
        if response.lower() != "yes":
            print("Aborted.")
            return
    
    print("\n" + "="*60)
    print("SURAKSH BACKEND ENVIRONMENT SETUP")
    print("="*60)
    print("\nThis script will create a .env file with required configuration.")
    print("You'll need to provide your LLM API key.\n")
    
    # Get LLM API key
    print("LLM Configuration:")
    print("1. Get an OpenRouter API key from https://openrouter.ai/")
    print("2. Or use OpenAI API key from https://platform.openai.com/api-keys")
    print()
    
    llm_api_key = input("Enter your LLM API key (or press Enter to skip): ").strip()
    
    if not llm_api_key:
        print("⚠️  No API key provided. You'll need to set LLM_API_KEY manually.")
        llm_api_key = "YOUR_API_KEY_HERE"
    
    # Get LLM provider
    print("\nLLM Provider:")
    print("1. openrouter (default, uses OpenRouter API)")
    print("2. openai (uses OpenAI directly)")
    provider = input("Enter provider (default: openrouter): ").strip() or "openrouter"
    
    # Get model
    if provider == "openrouter":
        model = input("Enter model (default: deepseek/deepseek-r1-0528:free): ").strip() or "deepseek/deepseek-r1-0528:free"
    else:
        model = input("Enter model (default: gpt-4o-mini): ").strip() or "gpt-4o-mini"
    
    # Create .env content
    env_content = f"""# Suraksh Backend Configuration
# Generated by setup_env.py

# LLM Configuration
LLM_PROVIDER={provider}
LLM_MODEL={model}
LLM_API_KEY={llm_api_key}
LLM_TEMPERATURE=0.1

# OpenRouter Configuration (if using OpenRouter)
OPENROUTER_BASE_URL=https://openrouter.ai/api/v1
OPENROUTER_HTTP_REFERER=https://suraksh.local
OPENROUTER_SITE_NAME=Suraksh Portal

# Database
DATABASE_URL=postgresql://suraksh:suraksh_pass@localhost:5432/suraksh_db

# Redis
REDIS_URL=redis://localhost:6379/0

# Neo4j
NEO4J_URI=bolt://localhost:7687
NEO4J_USER=neo4j
NEO4J_PASSWORD=your_neo4j_password_here

# Qdrant
QDRANT_URL=http://localhost:6333
QDRANT_COLLECTION_NAME=suraksh_documents

# MinIO
MINIO_ENDPOINT=localhost:9000
MINIO_ACCESS_KEY=minioadmin
MINIO_SECRET_KEY=minioadmin123
MINIO_BUCKET_NAME=suraksh-vault
MINIO_SECURE=False

# JWT
JWT_SECRET_KEY=change-me-in-production-use-strong-random-key
JWT_ALGORITHM=HS256
JWT_ACCESS_TOKEN_EXPIRE_MINUTES=30

# Application
DEBUG=True
ENVIRONMENT=development
CORS_ORIGINS=http://localhost:3000,http://localhost:3002,http://localhost:8000
"""
    
    # Write .env file
    try:
        with open(env_path, "w") as f:
            f.write(env_content)
        print(f"\n✅ .env file created at {env_path}")
        print("\n⚠️  IMPORTANT: Update the following values:")
        print("   - NEO4J_PASSWORD: Set your Neo4j password")
        print("   - JWT_SECRET_KEY: Change to a strong random key in production")
        if llm_api_key == "YOUR_API_KEY_HERE":
            print("   - LLM_API_KEY: Set your actual API key")
    except Exception as e:
        print(f"\n❌ Failed to create .env file: {e}")
        return
    
    print("\n" + "="*60)
    print("SETUP COMPLETE")
    print("="*60)
    print("\nNext steps:")
    print("1. Update NEO4J_PASSWORD in .env file")
    print("2. If LLM_API_KEY is not set, add your API key")
    print("3. Restart the backend server")
    print("\nTo test the setup, run:")
    print("  python backend/scripts/test_extraction.py")


if __name__ == "__main__":
    create_env_file()

